# Generated by Django 5.0.7 on 2024-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(default='anonim', max_length=50, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликована')], default='DRAFT', max_length=10, verbose_name='Статус'),
        ),
    ]
